const pool = require('../db/pool');

const medicines = [
  { name: 'Amoxicillin', generic_name: 'Amoxicillin Trihydrate', category: 'Antibiotic', species: 'Dog, Cat, Cattle, Horse', dosage: '10-20 mg/kg PO/IM q12h', description: 'Broad-spectrum penicillin antibiotic effective against gram-positive and some gram-negative bacteria.', indications: 'Respiratory infections, urinary tract infections, skin infections, wound infections', contraindications: 'Hypersensitivity to penicillins, rabbits, guinea pigs, hamsters', side_effects: 'Gastrointestinal upset, allergic reactions, diarrhea', brand_names: 'Amoxil, Clamoxyl, Moxilin' },
  { name: 'Amoxicillin-Clavulanic Acid', generic_name: 'Amoxicillin + Clavulanate Potassium', category: 'Antibiotic', species: 'Dog, Cat', dosage: '12.5-25 mg/kg PO q12h', description: 'Broad-spectrum antibiotic with beta-lactamase inhibitor for resistant bacterial infections.', indications: 'Pyoderma, urinary tract infections, periodontitis, soft tissue infections', contraindications: 'Hypersensitivity to penicillins, severe renal impairment', side_effects: 'Vomiting, diarrhea, anorexia', brand_names: 'Clavamox, Synulox, Augmentin' },
  { name: 'Cefpodoxime', generic_name: 'Cefpodoxime Proxetil', category: 'Antibiotic', species: 'Dog, Cat', dosage: '5-10 mg/kg PO q24h', description: 'Third-generation cephalosporin with broad-spectrum activity.', indications: 'Pyoderma, urinary tract infections, wound infections', contraindications: 'Hypersensitivity to cephalosporins', side_effects: 'Vomiting, diarrhea, decreased appetite', brand_names: 'Simplicef, Vantin' },
  { name: 'Enrofloxacin', generic_name: 'Enrofloxacin', category: 'Antibiotic', species: 'Dog, Cat, Bird, Reptile', dosage: '5-20 mg/kg PO/IM q24h', description: 'Fluoroquinolone antibiotic with broad-spectrum gram-negative coverage.', indications: 'UTI, prostatitis, respiratory infections, wound infections, septicemia', contraindications: 'Growing puppies (under 8 months), cats with CNS disorders, cartilage damage in young', side_effects: 'Vomiting, diarrhea, CNS stimulation, cartilage damage in young animals', brand_names: 'Baytril, Enroxil, Floxabactin' },
  { name: 'Doxycycline', generic_name: 'Doxycycline Hyclate', category: 'Antibiotic', species: 'Dog, Cat, Horse, Bird', dosage: '5-10 mg/kg PO q12-24h', description: 'Tetracycline antibiotic effective against intracellular bacteria and atypical pathogens.', indications: 'Ehrlichiosis, anaplasmosis, leptospirosis, respiratory infections, Lyme disease', contraindications: 'Young animals (teeth discoloration), hepatic impairment', side_effects: 'Vomiting, esophagitis, photosensitivity, teeth discoloration', brand_names: 'Vibramycin, Doxirobe, Ronaxan' },
  { name: 'Metronidazole', generic_name: 'Metronidazole', category: 'Antibiotic', species: 'Dog, Cat, Horse', dosage: '10-25 mg/kg PO q12h', description: 'Nitroimidazole antibiotic effective against anaerobic bacteria and protozoa.', indications: 'Giardiasis, anaerobic infections, periodontal disease, IBD, hepatic encephalopathy', contraindications: 'Pregnancy, hepatic disease, CNS disorders', side_effects: 'Vomiting, anorexia, neurotoxicity (ataxia, nystagmus)', brand_names: 'Flagyl, Metrogyl, Vetricide' },
  { name: 'Meloxicam', generic_name: 'Meloxicam', category: 'Anti-inflammatory', species: 'Dog, Cat', dosage: 'Dog: 0.2 mg/kg PO on day 1 then 0.1 mg/kg q24h; Cat: 0.05 mg/kg PO q24h', description: 'NSAID of the oxicam class with COX-2 selective anti-inflammatory activity.', indications: 'Osteoarthritis, post-operative pain, musculoskeletal inflammation', contraindications: 'Dehydration, renal disease, GI ulceration, concurrent corticosteroid use', side_effects: 'GI upset, renal toxicity, hepatic enzyme elevation, GI bleeding', brand_names: 'Metacam, Meloxidyl, Loxicom, Inflacam' },
  { name: 'Carprofen', generic_name: 'Carprofen', category: 'Anti-inflammatory', species: 'Dog', dosage: '2.2 mg/kg PO q12h or 4.4 mg/kg PO q24h', description: 'NSAID with COX-2 preferential activity for canine pain and inflammation.', indications: 'Post-operative pain, osteoarthritis, musculoskeletal inflammation', contraindications: 'Renal disease, hepatic disease, GI ulceration, Doberman Pinschers (higher risk)', side_effects: 'Vomiting, diarrhea, hepatic toxicity, renal toxicity', brand_names: 'Rimadyl, Novox, Carprieve, Carprodyl' },
  { name: 'Prednisolone', generic_name: 'Prednisolone', category: 'Anti-inflammatory', species: 'Dog, Cat, Horse', dosage: '0.5-2 mg/kg PO q12-24h', description: 'Corticosteroid with potent anti-inflammatory and immunosuppressive properties.', indications: 'Allergic reactions, immune-mediated diseases, inflammatory conditions, shock', contraindications: 'Systemic fungal infections, diabetes, glaucoma, active infections', side_effects: 'Polydipsia, polyuria, polyphagia, immunosuppression, muscle wasting', brand_names: 'Prednisole, Prelone, Solone' },
  { name: 'Dexamethasone', generic_name: 'Dexamethasone', category: 'Anti-inflammatory', species: 'Dog, Cat, Horse, Cattle', dosage: '0.1-2 mg/kg IV/IM/PO q24h', description: 'Potent long-acting corticosteroid with strong anti-inflammatory and immunosuppressive activity.', indications: 'Shock, cerebral edema, severe allergic reactions, inflammatory conditions', contraindications: 'Systemic fungal infections, active infections, GI ulcers', side_effects: 'PU/PD, immunosuppression, GI ulceration, delayed wound healing', brand_names: 'Dexaject, Dexasone, Azium, Rapidexon' },
  { name: 'Ivermectin', generic_name: 'Ivermectin', category: 'Antiparasitic', species: 'Dog, Cat, Cattle, Sheep, Horse', dosage: 'Dog: 0.006-0.2 mg/kg PO; Cattle: 0.2 mg/kg SC', description: 'Macrocyclic lactone antiparasitic effective against nematodes and ectoparasites.', indications: 'Heartworm prevention, sarcoptic mange, ear mites, intestinal nematodes, demodicosis (high dose)', contraindications: 'Collies and herding breeds with MDR1 mutation (neurotoxic), kittens under 6 weeks', side_effects: 'Mydriasis, ataxia, tremors, coma, death (in sensitive breeds)', brand_names: 'Ivomec, Heartgard, Panomec, Noromectin' },
  { name: 'Praziquantel', generic_name: 'Praziquantel', category: 'Antiparasitic', species: 'Dog, Cat, Horse', dosage: '5 mg/kg PO/SC (cestodes); 25 mg/kg PO (trematodes)', description: 'Cestocide effective against tapeworms and flukes.', indications: 'Tapeworm infections (Taenia, Dipylidium, Echinococcus)', contraindications: 'Puppies under 4 weeks', side_effects: 'Vomiting, diarrhea, anorexia (rare)', brand_names: 'Droncit, Drontal (combination), Prazitel' },
  { name: 'Fenbendazole', generic_name: 'Fenbendazole', category: 'Antiparasitic', species: 'Dog, Cat, Horse, Cattle', dosage: '50 mg/kg PO q24h for 3 days', description: 'Broad-spectrum benzimidazole anthelmintic.', indications: 'Roundworms, hookworms, whipworms, giardia, lungworms', contraindications: 'None significant', side_effects: 'Vomiting, diarrhea (rare)', brand_names: 'Panacur, Safe-Guard, Fenben' },
  { name: 'Fipronil', generic_name: 'Fipronil', category: 'Antiparasitic', species: 'Dog, Cat', dosage: 'Topical: 0.5-1 mL applied to skin', description: 'Phenylpyrazole insecticide/acaricide for topical ectoparasite control.', indications: 'Flea infestation, tick infestation, chewing lice', contraindications: 'Rabbits (severe toxicity), kittens under 8 weeks', side_effects: 'Local skin irritation, hypersalivation (if ingested)', brand_names: 'Frontline, FiLine, Fleasafe' },
  { name: 'Ketoconazole', generic_name: 'Ketoconazole', category: 'Antifungal', species: 'Dog, Cat', dosage: '10-15 mg/kg PO q12-24h', description: 'Imidazole antifungal agent with broad-spectrum activity.', indications: 'Dermatophytosis, systemic mycoses, Malassezia dermatitis, Cushings (adjunct)', contraindications: 'Hepatic disease, pregnancy, concurrent terfenadine/astemizole', side_effects: 'Hepatotoxicity, vomiting, anorexia, pruritus', brand_names: 'Nizoral, Ketocon, Fungoral' },
  { name: 'Itraconazole', generic_name: 'Itraconazole', category: 'Antifungal', species: 'Dog, Cat', dosage: '5-10 mg/kg PO q12-24h', description: 'Triazole antifungal with better safety profile than ketoconazole.', indications: 'Dermatophytosis, systemic mycoses, blastomycosis, histoplasmosis', contraindications: 'Hepatic disease, pregnancy', side_effects: 'Hepatotoxicity, anorexia, nausea', brand_names: 'Sporanox, Itrafungol, Itrazole' },
  { name: 'Terbinafine', generic_name: 'Terbinafine Hydrochloride', category: 'Antifungal', species: 'Dog, Cat', dosage: '30-40 mg/kg PO q24h', description: 'Allylamine antifungal agent with fungicidal activity.', indications: 'Dermatophytosis (refractory cases), ringworm', contraindications: 'Hepatic disease', side_effects: 'Gastrointestinal upset, hepatotoxicity (rare)', brand_names: 'Lamisil, Terbifine, Fungistop' },
  { name: 'Interferon Omega', generic_name: 'Recombinant Feline Interferon Omega', category: 'Antiviral', species: 'Cat', dosage: '1 MU/kg IV/SC q24h for 3-5 days', description: 'Recombinant feline interferon with antiviral and immunomodulatory properties.', indications: 'Feline parvovirus, FIV, FeLV, feline herpesvirus', contraindications: 'None significant', side_effects: 'Mild transient fever', brand_names: 'Virbagen Omega, Felomega' },
  { name: 'Xylazine', generic_name: 'Xylazine Hydrochloride', category: 'Anaesthesia', species: 'Dog, Cat, Horse, Cattle', dosage: 'Dog: 0.5-2 mg/kg IV/IM; Cat: 0.5-1 mg/kg IM', description: 'Alpha-2 adrenergic agonist sedative, analgesic, and muscle relaxant.', indications: 'Sedation, pre-anesthetic medication, anesthetic induction, emetic (cats)', contraindications: 'Advanced renal/hepatic disease, respiratory compromise, pregnancy', side_effects: 'Vomiting, bradycardia, hypotension, respiratory depression', brand_names: 'Rompun, Xylacare, Anased, Sedaxylan' },
  { name: 'Ketamine', generic_name: 'Ketamine Hydrochloride', category: 'Anaesthesia', species: 'Dog, Cat, Horse', dosage: 'Dog: 5-30 mg/kg IM/IV; Cat: 10-30 mg/kg IM/IV', description: 'Dissociative anesthetic agent with NMDA antagonist activity.', indications: 'Anesthetic induction, short-term anesthesia, adjunct to analgesic protocols', contraindications: 'Hypertension, glaucoma, head trauma, seizure disorders', side_effects: 'Hypertension, salivation, muscle rigidity, emergence delirium', brand_names: 'Ketaset, Vetalar, Ketavet, Narketan' },
  { name: 'Propofol', generic_name: 'Propofol', category: 'Anaesthesia', species: 'Dog, Cat', dosage: '4-8 mg/kg IV to effect', description: 'Short-acting intravenous anesthetic agent.', indications: 'Anesthetic induction, maintenance of anesthesia, short procedures', contraindications: 'Hypotension, hypoproteinemia, respiratory compromise', side_effects: 'Respiratory depression, hypotension, apnea, pain on injection', brand_names: 'Propofol, Rapinovet, Diprivan' },
  { name: 'Atropine', generic_name: 'Atropine Sulfate', category: 'Anaesthesia', species: 'Dog, Cat, Horse, Cattle', dosage: '0.02-0.04 mg/kg IV/IM/SC', description: 'Anticholinergic agent used to counteract bradycardia and reduce secretions.', indications: 'Pre-anesthetic medication, bradycardia treatment, organophosphate poisoning', contraindications: 'Glaucoma, GI obstruction, tachycardia', side_effects: 'Mydriasis, tachycardia, dry mucous membranes, ileus', brand_names: 'Atropine Sulfate, Atroject, Iso-Athamine' },
  { name: 'Insulin (NPH)', generic_name: 'Neutral Protamine Hagedorn Insulin', category: 'Hormone', species: 'Dog, Cat', dosage: 'Dog: 0.25-0.5 U/kg SC q12h; Cat: 0.1-0.3 U/kg SC q12h', description: 'Intermediate-acting insulin for diabetes mellitus management.', indications: 'Diabetes mellitus', contraindications: 'Hypoglycemia, insulinoma', side_effects: 'Hypoglycemia, insulin resistance, lipodystrophy at injection site', brand_names: 'Humulin N, Novolin N, Caninsulin' },
  { name: 'Thyroxine (Levothyroxine)', generic_name: 'Levothyroxine Sodium', category: 'Hormone', species: 'Dog', dosage: '0.02 mg/kg PO q12h', description: 'Synthetic T4 hormone replacement for hypothyroidism.', indications: 'Hypothyroidism, myxedema coma', contraindications: 'Hyperthyroidism, recent MI, adrenal insufficiency', side_effects: 'Tachycardia, hypertension, weight loss, panting, hyperactivity', brand_names: 'Soloxine, Thyro-Tabs, Forthyron' },
  { name: 'Methimazole', generic_name: 'Methimazole', category: 'Hormone', species: 'Cat', dosage: '2.5-5 mg PO q12h', description: 'Thyroid hormone synthesis inhibitor for feline hyperthyroidism.', indications: 'Feline hyperthyroidism, thyroid storm', contraindications: 'Hepatic disease, pregnancy, autoimmune disease', side_effects: 'Vomiting, anorexia, hepatopathy, facial pruritus, agranulocytosis', brand_names: 'Felimazole, Tapazole, Methizole' },
  { name: 'Vitamin B12', generic_name: 'Cyanocobalamin', category: 'Vitamin', species: 'Dog, Cat, Horse', dosage: 'Dog: 100-500 mcg IM/SC; Cat: 50-100 mcg IM/SC', description: 'Water-soluble vitamin essential for neurologic function and erythropoiesis.', indications: 'Vitamin B12 deficiency, chronic GI disease, pernicious anemia, supportive care', contraindications: 'None significant', side_effects: 'None significant', brand_names: 'Cobalac, Vitamin B12, Cobalex' },
  { name: 'Vitamin K1', generic_name: 'Phytonadione', category: 'Vitamin', species: 'Dog, Cat', dosage: '3-5 mg/kg SC/PO q12h', description: 'Fat-soluble vitamin essential for hepatic synthesis of clotting factors.', indications: 'Anticoagulant rodenticide toxicity, vitamin K deficiency', contraindications: 'None significant (IV administration may cause anaphylaxis)', side_effects: 'Local injection site reaction, anaphylaxis (IV route)', brand_names: 'Mephyton, Aquamephyton, Vitamin K1' },
  { name: 'Furosemide', generic_name: 'Furosemide', category: 'Other', species: 'Dog, Cat, Horse', dosage: '1-4 mg/kg IV/IM/PO q8-12h', description: 'Loop diuretic used for pulmonary edema and congestive heart failure.', indications: 'Pulmonary edema, congestive heart failure, ascites, hypercalcemia', contraindications: 'Anuria, severe renal failure, dehydration, hypokalemia', side_effects: 'Dehydration, hypokalemia, hypochloremia, ototoxicity, renal failure', brand_names: 'Lasix, Disal, Frusemide, Diurin' },
  { name: 'Enalapril', generic_name: 'Enalapril Maleate', category: 'Other', species: 'Dog, Cat', dosage: '0.25-0.5 mg/kg PO q12-24h', description: 'ACE inhibitor used for heart failure and hypertension.', indications: 'Congestive heart failure, hypertension, chronic renal disease, proteinuria', contraindications: 'Hypotension, renal artery stenosis, pregnancy', side_effects: 'Hypotension, azotemia, hyperkalemia, cough', brand_names: 'Enacard, Vasotec, Enalaprilum' },
  { name: 'Omeprazole', generic_name: 'Omeprazole', category: 'Other', species: 'Dog, Cat, Horse', dosage: 'Dog: 0.5-1 mg/kg PO q12-24h; Cat: 0.7-1 mg/kg PO q24h', description: 'Proton pump inhibitor for gastric acid suppression.', indications: 'GI ulceration, esophagitis, gastritis, GERD', contraindications: 'None significant', side_effects: 'Vomiting, diarrhea, hypergastrinemia (long term)', brand_names: 'GastroGard, Prilosec, Losec, Omeprazole' },
  { name: 'Ranitidine', generic_name: 'Ranitidine Hydrochloride', category: 'Other', species: 'Dog, Cat, Horse', dosage: '1-2 mg/kg IV/PO q8-12h', description: 'H2 receptor antagonist for gastric acid suppression.', indications: 'GI ulceration, gastritis, GERD, esophagitis', contraindications: 'Severe renal disease', side_effects: 'Vomiting, diarrhea (rare), headache', brand_names: 'Zantac, Ranitidine, Raniject' },
  { name: 'Maropitant', generic_name: 'Maropitant Citrate', category: 'Other', species: 'Dog, Cat', dosage: 'Dog: 1-2 mg/kg SC/PO q24h; Cat: 1 mg/kg SC q24h', description: 'Neurokinin-1 receptor antagonist for prevention of vomiting.', indications: 'Prevention of chemotherapy-induced emesis, motion sickness, acute vomiting', contraindications: 'Puppies under 8 weeks, GI obstruction', side_effects: 'Hypersalivation, drowsiness, diarrhea', brand_names: 'Cerenia, Maropitant, Preventic' },
  { name: 'Diphenhydramine', generic_name: 'Diphenhydramine Hydrochloride', category: 'Other', species: 'Dog, Cat', dosage: '1-2 mg/kg PO/IM q8-12h', description: 'First-generation H1 antihistamine.', indications: 'Allergic reactions, urticaria, motion sickness, sedation, mast cell tumors (adjunct)', contraindications: 'Glaucoma, urinary retention, hyperthyroidism, cardiac disease', side_effects: 'Sedation, paradoxical excitation, dry mouth, urinary retention', brand_names: 'Benadryl, Diphen, Histaminex' },
  { name: 'Rabies Vaccine', generic_name: 'Inactivated Rabies Virus', category: 'Vaccine', species: 'Dog, Cat, Horse, Cattle', dosage: '1 mL IM/SC, annual or triennial booster', description: 'Inactivated virus vaccine for prevention of rabies.', indications: 'Core vaccination for dogs, cats, and horses', contraindications: 'Pregnancy (labeled), febrile illness, immunosuppression', side_effects: 'Local injection site reaction, lethargy, vaccine-site sarcoma (cats)', brand_names: 'Rabisin, Nobivac Rabies, Imrab, Defensor' },
  { name: 'DHPP Vaccine', generic_name: 'Modified Live Distemper, Hepatitis, Parvovirus, Parainfluenza', category: 'Vaccine', species: 'Dog', dosage: '1 mL SC, initial course of 2-3 boosters', description: 'Combination MLV vaccine for core canine diseases.', indications: 'Core vaccination for puppies and adult dogs', contraindications: 'Pregnancy, immunosuppression, febrile illness', side_effects: 'Mild lethargy, transient fever, local reaction', brand_names: 'Nobivac DHPP, Vanguard, Quantum, Duramune' },
  { name: 'FVRCP Vaccine', generic_name: 'Modified Live Feline Viral Rhinotracheitis, Calicivirus, Panleukopenia', category: 'Vaccine', species: 'Cat', dosage: '1 mL SC, initial course of 2-3 boosters', description: 'Combination MLV vaccine for core feline diseases.', indications: 'Core vaccination for kittens and adult cats', contraindications: 'Pregnancy, immunosuppression, febrile illness', side_effects: 'Mild lethargy, sneezing, ocular discharge, limping (rare)', brand_names: 'Nobivac Feline, Fel-O-Vax, PureVax' },
  { name: 'Lactated Ringers Solution', generic_name: 'Lactated Ringers Injection USP', category: 'Fluid', species: 'Dog, Cat, Horse, Cattle', dosage: 'Shock: 60-90 mL/kg IV; Maintenance: 40-60 mL/kg/day IV', description: 'Isotonic crystalloid solution for fluid resuscitation and maintenance.', indications: 'Dehydration, hypovolemia, shock, electrolyte replacement, metabolic acidosis', contraindications: 'Severe hyperkalemia, hypercalcemia, metabolic alkalosis, CHF with pulmonary edema', side_effects: 'Volume overload, phlebitis, hyperkalemia', brand_names: 'Lactated Ringers, LR, Ringer Lactate' },
  { name: 'Normal Saline', generic_name: '0.9% Sodium Chloride', category: 'Fluid', species: 'Dog, Cat, Horse, Cattle', dosage: 'Shock: 60-90 mL/kg IV; Maintenance: 40-60 mL/kg/day IV', description: 'Isotonic crystalloid solution of sodium chloride in water.', indications: 'Dehydration, hyponatremia, hypovolemia, fluid therapy, drug administration', contraindications: 'Hypernatremia, metabolic alkalosis, CHF', side_effects: 'Volume overload, hypernatremia, hypokalemia', brand_names: 'Normal Saline, 0.9% NaCl, Saline' },
  { name: 'Dextrose 5%', generic_name: 'Dextrose 5% in Water', category: 'Fluid', species: 'Dog, Cat, Horse', dosage: '2-5 mL/kg/h IV', description: 'Hypotonic crystalloid solution providing free water and energy.', indications: 'Hypoglycemia, maintenance fluid therapy, hypernatremia', contraindications: 'Intracranial hemorrhage, severe dehydration (initially), hyperglycemia', side_effects: 'Hyperglycemia, hyponatremia, volume overload', brand_names: 'D5W, Dextrose 5%, Glucose 5%' },
  { name: 'Diazepam', generic_name: 'Diazepam', category: 'Other', species: 'Dog, Cat, Horse', dosage: 'Dog: 0.5-2 mg/kg IV; Cat: 0.2-0.5 mg/kg IV/PO', description: 'Benzodiazepine with anticonvulsant, anxiolytic, and muscle relaxant properties.', indications: 'Status epilepticus, seizures, anxiety, pre-anesthetic medication, appetite stimulant (cats)', contraindications: 'Severe hepatic disease, glaucoma, myasthenia gravis', side_effects: 'Sedation, ataxia, paradoxical excitation, hepatic failure (cats - oral)', brand_names: 'Valium, Diazepam, Pam' },
  { name: 'Phenobarbital', generic_name: 'Phenobarbital Sodium', category: 'Other', species: 'Dog, Cat', dosage: 'Dog: 2-5 mg/kg PO q12h; Loading: 12-20 mg/kg IV/PO divided', description: 'Barbiturate anticonvulsant for long-term seizure management.', indications: 'Idiopathic epilepsy, seizure disorders, status epilepticus', contraindications: 'Severe hepatic disease, respiratory compromise', side_effects: 'Sedation, ataxia, polydipsia, polyuria, PU/PD, hepatotoxicity, blood dyscrasias', brand_names: 'Phenobarbital, Luminal, Barbital' },
];

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const existing = await client.query('SELECT COUNT(*) FROM medicines');
    if (parseInt(existing.rows[0].count) > 0) {
      console.log('Medicines table already has ' + existing.rows[0].count + ' entries, skipping seed');
      return;
    }
    for (const m of medicines) {
      await client.query(
        `INSERT INTO medicines (name, generic_name, category, species, dosage, description, indications, contraindications, side_effects, brand_names)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
        [m.name, m.generic_name, m.category, m.species, m.dosage, m.description, m.indications, m.contraindications, m.side_effects, m.brand_names]
      );
    }
    await client.query('COMMIT');
    console.log(`Seeded ${medicines.length} veterinary medicines`);
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err.message);
  } finally {
    client.release();
    pool.end();
  }
}

seed();
